commonLabels:
  team: ninjas

commonAnnotations:
  preFix: 3/22/2019

namePrefix: mykustomizer-

#namePostfix: -yabadabado

resources:
- ingress.yaml

patchesJson6902:
- target:
    group: extensions
    version: v1beta1
    kind: Ingress
    name: my-ingress
  path: ingress_patch.json
